### ISSUE TITLE
System.exit(0) is not recommended

### ISSUE THREAD

**Issue by IgorGanapolsky** [sterlp/training#1]
Hi,
in your sample, you are calling **System.exit(0)** in the Activity.  However, it is not a recommended practice, as it doesn't clean up the task stack.  Furthermore, you already called **android.os.Process.killProcess** right before that, so it is redundant.

Please let me know your thoughts on this.

Thank you,
Igor

**Comment by sterlp** [comment]
Hello Igor,

I agree with you. I had the observation on older android version (4.3) that somehow it doesn't always really work to 100% having killProcess in place. As so I added the System.exit(0) -- which is redundant here. Overall it would be better to apply the strategy pattern and call System.exit(0) only on older android version; where I observed this misbehavior.

Thanks

Paul

**Comment by IgorGanapolsky** [comment]
Yes it makes sense, thanks.  Actually Process.killProcess doesn't kill sticky Services,  or TimerTasks.  If if using this pattern, it may be necessary to use System.exit(0) in conjunction...
